java_test(
    name = "FooTest",
    srcs = ["FooTest.java"],
    test_class = "foo.FooTest",
    deps = [
        "//java/client/src/foo:Foo",
        "//thirdparty/java/junit:junit",
        "//thirdparty/java/junit:hamcrest",
        "//thirdparty/java/async-http-client",
        "//thirdparty/java/netty",
        "//thirdparty/java/reactive-streams",
    ],
)
